/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PointsReward = IDL.Nat;
export const OfferId = IDL.Nat;
export const Points = IDL.Nat;
export const Offer = IDL.Record({
  'id' : OfferId,
  'name' : IDL.Text,
  'requiredPoints' : PointsReward,
  'rewardDescription' : IDL.Text,
});

export const idlService = IDL.Service({
  'addOffer' : IDL.Func([IDL.Text, PointsReward, IDL.Text], [OfferId], []),
  'addPoints' : IDL.Func([IDL.Principal, Points], [], []),
  'authenticate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteOffer' : IDL.Func([OfferId], [], []),
  'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'redeemOffer' : IDL.Func([IDL.Principal, OfferId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PointsReward = IDL.Nat;
  const OfferId = IDL.Nat;
  const Points = IDL.Nat;
  const Offer = IDL.Record({
    'id' : OfferId,
    'name' : IDL.Text,
    'requiredPoints' : PointsReward,
    'rewardDescription' : IDL.Text,
  });
  
  return IDL.Service({
    'addOffer' : IDL.Func([IDL.Text, PointsReward, IDL.Text], [OfferId], []),
    'addPoints' : IDL.Func([IDL.Principal, Points], [], []),
    'authenticate' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteOffer' : IDL.Func([OfferId], [], []),
    'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'redeemOffer' : IDL.Func([IDL.Principal, OfferId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };