/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Offer {
  'id' : OfferId,
  'name' : string,
  'requiredPoints' : PointsReward,
  'rewardDescription' : string,
}
export type OfferId = bigint;
export type Points = bigint;
export type PointsReward = bigint;
export interface _SERVICE {
  'addOffer' : ActorMethod<[string, PointsReward, string], OfferId>,
  'addPoints' : ActorMethod<[Principal, Points], undefined>,
  'authenticate' : ActorMethod<[string, string], boolean>,
  'deleteOffer' : ActorMethod<[OfferId], undefined>,
  'getAllOffers' : ActorMethod<[], Array<Offer>>,
  'initialize' : ActorMethod<[], undefined>,
  'redeemOffer' : ActorMethod<[Principal, OfferId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];